require "action-controller/logger"
require "secrets-env"

module App
  NAME    = "Wallet-Api"
  VERSION = {{ `shards version "#{__DIR__}"`.chomp.stringify.downcase }}

  Log         = ::Log.for(NAME)
  LOG_BACKEND = ActionController.default_backend

  ENVIRONMENT = ENV["SG_ENV"]? || "development"

  DEFAULT_PORT          = (ENV["SG_SERVER_PORT"]? || 3000).to_i
  DEFAULT_HOST          = ENV["SG_SERVER_HOST"]? || "127.0.0.1"
  DEFAULT_PROCESS_COUNT = (ENV["SG_PROCESS_COUNT"]? || 1).to_i

  STATIC_FILE_PATH = ENV["PUBLIC_WWW_PATH"]? || "./www"

  COOKIE_SESSION_KEY    = ENV["COOKIE_SESSION_KEY"]? || "_spider_gazelle_"
  COOKIE_SESSION_SECRET = ENV["COOKIE_SESSION_SECRET"]? || "4f74c0b358d5bab4000dd3c75465dc2c"

  # General
  API_KEY = ENV["API_KEY"]?

  # # Environment Variables
  # Google
  GOOGLE_PRIVATE_KEY        = ENV["GOOGLE_PRIVATE_KEY"]
  GOOGLE_CLIENT_EMAIL       = ENV["GOOGLE_CLIENT_EMAIL"]
  GOOGLE_WALLET_ISSUER_ID   = ENV["GOOGLE_WALLET_ISSUER_ID"]
  GOOGLE_WALLET_ISSUER_NAME = ENV["GOOGLE_WALLET_ISSUER_NAME"]
  GOOGLE_LOGO_IMAGE_URL     = ENV["GOOGLE_LOGO_IMAGE_URL"]?
  GOOGLE_LOGO_DESCRIPTION   = ENV["GOOGLE_LOGO_DESCRIPTION"]?

  # Apple
  APPLE_PASS_TYPE_IDENTIFIER    = ENV["APPLE_PASS_TYPE_IDENTIFIER"]
  APPLE_TEAM_IDENTIFIER         = ENV["APPLE_TEAM_IDENTIFIER"]
  APPLE_ORGANIZATION_NAME       = ENV["APPLE_ORGANIZATION_NAME"]
  APPLE_DESIGN_FOREGROUND_COLOR = ENV["APPLE_DESIGN_FOREGROUND_COLOR"]
  APPLE_DESIGN_BACKGROUND_COLOR = ENV["APPLE_DESIGN_BACKGROUND_COLOR"]
  APPLE_DESIGN_LABEL_COLOR      = ENV["APPLE_DESIGN_LABEL_COLOR"]
  APPLE_LOGO_PATH               = ENV["APPLE_LOGO_PATH"]
  APPLE_ICON_PATH               = ENV["APPLE_ICON_PATH"]
  APPLE_LOGO_DESCRIPTION        = ENV["APPLE_LOGO_DESCRIPTION"]

  # AWS
  AWS_REGION = ENV["AWS_REGION"]
  AWS_KEY    = ENV["AWS_KEY"]
  AWS_SECRET = ENV["AWS_SECRET"]
  AWS_BUCKET = ENV["AWS_BUCKET"]

  class_getter? production = ENVIRONMENT.downcase == "production"
end
